version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          # key: <projectname>-{{ .Branch }}-{{ checksum "Pipfile.lock" }}  projectname can be anything, so long as it matches save_cache below.
          key: deps-1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install pipenv
            pipenv install --dev --skip-lock
            pipenv install -e . --skip-lock # pytest recommends this: install your package in "editable" mode by running this from the same directory
            # pipenv will use requirements.txt with these params.
      - save_cache:
          key: deps-1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Running tests and test coverage
          command: |
            pipenv install coveralls --skip-lock # for coveralls.io -- this can be in Pipfile [dev] instead.
            pipenv run coverage run setup.py test
            pipenv run pytest tests --junit-xml=htmlcov/junit.xml # rerun tests to collect test-results
            pipenv run coverage report
            pipenv run coverage html
            pipenv run coveralls
            # set COVERALLS_REPO_TOKEN=<...> in ENVIRONMENT variables in circleci
            # pipenv run coverage run --omit '*tests*','*/home/*' setup.py test
            # moved omit to setup.cfg; broke on circleci - no uploads

      - store_test_results:
          path: htmlcov

      - store_artifacts:
          path: htmlcov
          destination: methylize
