name: Run PyTest
on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  COVERALLS_SERVICE_NAME: 'github'
  COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      #- name: Dump runner context
      #  run: echo '${{ toJSON(runner) }}'
      #- name: Dump strategy context
      #  run: echo '${{ toJSON(strategy) }}'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
            pip install pipenv pytest_cov
            # pipenv install pytest_cov
            pipenv install --dev --skip-lock
            pipenv install -e . --skip-lock
            # pipenv uses requirements.txt

      - name: Testing and coverage report
        run: |
          pipenv run coverage run setup.py test
          pipenv run coverage xml

      - name: Send to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #files: ./coverage.xml #./coverage1.xml,./coverage2.xml # optional
          directory: ./
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Publish Test Results to Github
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()

# GHA workflow: diffs are limited to 300 files. If there are files changed that aren't matched in the first 300 files returned by the
# filter, the workflow will not run. You may need to create more specific filters so that the workflow will run automatically.
