name: Run PyTest
on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  COVERALLS_SERVICE_NAME: 'github'
  COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2 # faster than python container
        with:
          python-version: 3.8

      - name: Setup & Cache Python
        run: |
            python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev --skip-lock
          pipenv install -e . --skip-lock
          # pipenv uses requirements.txt

      - name: Running tests and test coverage
        run: |
            # pipenv install coveralls --skip-lock # for coveralls.io -- this IS in Pipfile [dev] instead.
            # --junit-xml=htmlcov/junit.xml # rerun tests to collect test-results
            pipenv run coverage run test -v            
            pipenv run coverage report
            pipenv run coverage html
            pipenv run coveralls

  parallel-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
            pip install pipenv pytest_cov
            pipenv install pytest_cov
            pipenv install --dev --skip-lock
            pipenv install -e . --skip-lock
            pipenv install coveralls --skip-lock
            # pipenv uses requirements.txt

      - name: coveralls_first_attempt
        run: |
          pipenv run pytest tests -s -v --cov=test-results --cov-report term && coveralls
          # term-missing && coveralls /tests

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.26
        if: always()
        with:
          files: test-results/**/*.xml

      - name: Coveralls Finished
        env:
          COVERALLS_SERVICE_NAME: 'GitHub CI'
          COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
        uses: AndreMiras/coveralls-python-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

# Diffs are limited to 300 files. If there are files changed that aren't matched in the first 300 files returned by the
# filter, the workflow will not run. You may need to create more specific filters so that the workflow will run automatically.
#       - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
# - generated xml file: /home/runner/work/methylize/methylize/htmlcov/junit.xml --
#    - name: Coveralls
#      # add secrets here: https://github.com/organizations/FoxoTech/settings/secrets/actions
#      env:
#        COVERALLS_SERVICE_NAME: 'GitHub CI'
#        COVERALLS_REPO_TOKEN : ${{ secrets.COVERALLS_REPO_TOKEN }}
#      uses: AndreMiras/coveralls-python-action@develop
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        parallel: true
#        flag-name: Unit Test
